import { test } from '@playwright/test';
import { LoginHelper } from '../pages/LoginHelper';
import { HomePage } from '../pages/HomePage';

test('authenticate', async ({ page }) => {
 test.setTimeout(180000);
    // 1. Login with credentials
    await LoginHelper.login(page);

    console.log('After login:', page.url());

    // 2. Check session after login
    console.log(
        'Cookies after login:',
        await page.context().cookies()
    );

    console.log(
        'Storage state:',
        await page.context().storageState()
    );

    // 3. Navigate to Home
    const homePage = new HomePage(page);

    await homePage.clickHome();
await homePage.navigateToModule("Sales New");
console.log("========== SALES STATE ==========");

console.log("URL:", page.url());

console.log(
    "Cookies:",
    await page.context().cookies()
);

console.log(
    "LocalStorage:",
    await page.evaluate(() => {
        return { ...localStorage };
    })
);

console.log("================================");
// Capture the URL generated by the application
const salesUrl = page.url();

console.log('Sales URL:', salesUrl);

// Save authentication cookies
await page.context().storageState({
    path: 'playwright/.auth/user.json'
});

// Save Sales URL separately
const fs = require('fs');

fs.writeFileSync(
    'playwright/.auth/sales-url.json',
    JSON.stringify({ salesUrl }, null, 2)
);

console.log('Authentication state saved ✅');
console.log('Sales URL saved ✅');
});